### PR TITLE
Add ability to restart the windows service.

### PR DESCRIPTION
**Pull request by mford1**
Change default service permissions so that it can be restarted by the interactive user or by the service user account.

### CODE REVIEW

**Comment by LukePulverenti** [comment]
Can you add links to documentation for those permission strings? thanks.

**Comment by mford1** [comment]
MSDN has one, but the best description I found was here:

http://blogs.msmvps.com/erikr/2007/09/26/set-permissions-on-a-specific-service-windows/

**Comment by LukePulverenti** [comment]
Ok, please add to the code via comments so that others can refer to it in the future.

**Comment by mford1** [comment]
Do contributors get supporter keys?  :)

**Pull request closed without merging**
