### PR TITLE
Logging Improvements to Support Development, Troubleshooting and Message Filtering

### PR DESCRIPTION
**Pull request by solabc16**
Motivation was to provide a transparent way in which to apply custom filters to messages being written to the log. This will assist in debugging/troubleshooting, as the log can be swamped by debug messages that are not always of interest or relevant to the task at hand. It will also allow a custom filters to be setup for those users that wish to maintain their existing power saving/HDD hibernation capabilities. A mechanism has been added to address the issue of debug messages being lost during startup, a single change in the calling code is required to take advantage of the improvement. Debugging support, that is independent of the logger itself, has also been added to assist with current and future development of the logging facility. The library is fully backwards compatible and all new functionality is implemented in such a way that it will not throw any exceptions.

Tested with beta releases up to and including 3.1.233-beta.

### CODE REVIEW

**Comment by LukePulverenti** [comment]
Does this compile with both .net core and the full .net framework? Admittedly it is a little complicated for my comfort level, specifically manual parsing of the server config file as well as the manual appending to the log file.

**Comment by solabc16** [comment]
Hello

Thanks for the comments, perhaps a litttle more is needed in terms of explanation and clarification, so let me address that.

- Yes, it compliles with both the NETSTANDARD1_6 and NET46 defines.

- The only additional reference is to System.Xml, which is fully supported on core: https://docs.microsoft.com/en-us/dotnet/core/api/system.xml#System_Xml

- We are not manually appending to any existing log, the logging function for developing/troubleshooting the log manager (NlogManager) itself is through necessity entirely standalone.

- The method call for this logging has a conditional attribute defined, so unless the library is built with DEBUG defined, all code related to this functionality effectively does not exist. This is the normal case for any beta/stable builds currently being published. (see documentation comments in the code for more details)

- With regard to reading the value of EnableDebugLevelLogging,  we are using XPath navigation to query information in the DOM, so this is not as crude as attempting to manipulate the file as raw text.

- The approach above was deemed to be the most sensible answer to the question "how do we get early access to the system configured value of this setting, without adding unnecessary complexity to either the library itself or its caller?" (i.e. adding dependencies on configuration managers)

- The worst outcome with respect to the above is that for some reason in the future the location of this configuration setting changes, which would result in the initial severity defauling to Info, which intentionally represents no change to the existing behaviour.

- As this would kind of change would be considered unlikely and unnecessary, it wasn't a convincing argument to overcomplicate the implementation.

- All changes have been implemented in such a way that the existing implementation and behaviour remain unchanged, whilst any calls to leverage the new functionality are by default fail safe and unable to introduce new or unexpected exceptions.

- James

**Comment by solabc16** [comment]
As a further update, to gain some confidence in the changes and get some real-world feedback, I've created a customised build of 3.1.235-beta for Synology/XPEnology.

This includes this PR and a tweaked version of MediaBrowser.Server.Mono.exe, the changes to MediaBrowser.Server.Mono.exe are straightforward in nature and detailed below for reference.

```
//
// Use new Constructor and ReloadLogger method available in PR #2304, which
// enables custom filters to be applied to the log and uses the configured
// LogSeverity level from initial startup, rather than switching back to Info
// until the configuration settings are read.
//

// var logManager = new NlogManager(appPaths.LogDirectoryPath, "server");
// logManager.ReloadLogger(LogSeverity.Info);

var logManager = new NlogManager(appPaths.LogDirectoryPath, "server", appPaths.ConfigurationDirectoryPath);
logManager.ReloadLogger();
```
Initial testing shows that this has resolved the issue of Debug messages being lost during application start-up.; on a normal build, the first three messages do not appear in the log.

```
2016-11-24 20:17:09.9023 Debug App: [LinuxMount] System PATH is currently set to [/var/packages/EmbyServer/scripts/utilities/sbin:/var/packages/EmbyServer/target/mono/bin:/var/packages/EmbyServer/target/ffmpeg/bin:/var/packages/EmbyServer/target/imagemagick/bin:/var/packages/EmbyServer/target/sqlite/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin].
2016-11-24 20:17:09.9026 Debug App: [LinuxMount] System path separator is [:].
2016-11-24 20:17:09.9026 Debug App: [LinuxMount] Mount point root is [/tmp/Emby].
2016-11-24 20:17:09.9026 Info App: [LinuxMount] Using version of [sudo] located at [/var/packages/EmbyServer/scripts/utilities/sbin/sudo].
2016-11-24 20:17:09.9026 Info App: [LinuxMount] Using version of [mount] located at [/var/packages/EmbyServer/scripts/utilities/sbin/mount].
2016-11-24 20:17:09.9026 Info App: [LinuxMount] Using version of [umount] located at [/var/packages/EmbyServer/scripts/utilities/sbin/umount].
2016-11-24 20:18:39.7072 Info App: [LinuxMount] Checking we can attempt to mount [/volume1/MyEmbyMedia/The Net (1995)/The Net (1995).iso], Extension = [.iso], Operating System = [Linux], Executables Available = [True].
2016-11-24 20:18:39.7097 Info App: [LinuxMount] Checking we can attempt to mount [/volume1/MyEmbyMedia/The Net (1995)/The Net (1995).iso], Extension = [.iso], Operating System = [Linux], Executables Available = [True].
2016-11-24 20:18:39.7111 Info App: [LinuxMount] Attempting to mount [/volume1/MyEmbyMedia/The Net (1995)/The Net (1995).iso].
2016-11-24 20:18:39.7111 Debug App: [LinuxMount] ISO will be mounted at [/tmp/Emby/e0e96631-e777-42fb-ad24-bb9fdc28aa65].
2016-11-24 20:18:39.7121 Debug App: [LinuxMount] Our current UID is [1037], GetUserId() returned [1037].
2016-11-24 20:18:39.7121 Debug App: [LinuxMount] Mount command [/var/packages/EmbyServer/scripts/utilities/sbin/sudo], mount arguments ["/var/packages/EmbyServer/scripts/utilities/sbin/mount" "/volume1/MyEmbyMedia/The Net (1995)/The Net (1995).iso" "/tmp/Emby/e0e96631-e777-42fb-ad24-bb9fdc28aa65"].
2016-11-24 20:18:42.8278 Debug App: [LinuxMount] Standard output from process is [].
2016-11-24 20:18:42.8285 Debug App: [LinuxMount] Standard error from process is [].
2016-11-24 20:18:42.8305 Info App: [LinuxMount] ISO mount completed successfully.
2016-11-24 20:18:44.8467 Info App: [LinuxMount] Attempting to unmount ISO [/volume1/MyEmbyMedia/The Net (1995)/The Net (1995).iso] mounted on [/tmp/Emby/e0e96631-e777-42fb-ad24-bb9fdc28aa65].
2016-11-24 20:18:44.8467 Debug App: [LinuxMount] Our current UID is [1037], GetUserId() returned [1037].
2016-11-24 20:18:44.8467 Debug App: [LinuxMount] Umount command [/var/packages/EmbyServer/scripts/utilities/sbin/sudo], umount arguments ["/var/packages/EmbyServer/scripts/utilities/sbin/umount" "/tmp/Emby/e0e96631-e777-42fb-ad24-bb9fdc28aa65"].
2016-11-24 20:18:47.9465 Debug App: [LinuxMount] Standard output from process is [].
2016-11-24 20:18:47.9465 Debug App: [LinuxMount] Standard error from process is [].
2016-11-24 20:18:47.9476 Info App: [LinuxMount] ISO unmount completed successfully.
```
A test build with DEBUG defined produced the following development/troubleshooint log for NlogManager itself, which highlights the new behaviours when used with the changes above and a custom set of filters defined.

```
2016-11-24T20:21:19.826Z : NlogManager constructor called, logDirectory is [/var/packages/EmbyServer/target/var/logs], logFileNamePrefix is [server], _severity is [Debug].
2016-11-24T20:21:20.029Z : NlogManager constructor called, logDirectory is [/var/packages/EmbyServer/target/var/logs], logFileNamePrefix is [server], configDirectory is [/var/packages/EmbyServer/target/var/config], _severity is [Debug].
2016-11-24T20:21:20.071Z : GetLogLevelFromConfig called, xmlConfigFile = [/var/packages/EmbyServer/target/var/config/system.xml], xmlElement = [/ServerConfiguration/EnableDebugLevelLogging], xmlValue = [true], debugFlag = [True].
2016-11-24T20:21:20.072Z : GetLogLevelFromConfig returning [Debug].
2016-11-24T20:21:20.072Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:20.072Z : ReloadLogger called, level = [Debug], LogFilePath (existing) = [].
2016-11-24T20:21:20.094Z : AddFileTarget called, path = [/var/packages/EmbyServer/target/var/logs/server-63615615680.txt], level = [Debug].
2016-11-24T20:21:20.094Z : RemoveTarget called, name = [ApplicationLogFileWrapper].
2016-11-24T20:21:20.160Z : AddLogTarget called, target.Name = [ApplicationLogFileWrapper], level = [Debug].
2016-11-24T20:21:20.160Z : GetLogLevel called, severity = [Debug].
2016-11-24T20:21:20.164Z : AddCustomFilters called, defaultLoggerNamePattern = [*], defaultRule.LoggerNamePattern = [*].
2016-11-24T20:21:20.208Z : Custom Configuration Loaded, Rule Count = [1].
2016-11-24T20:21:20.209Z : Read Custom Rule, LoggerNamePattern = [*], Targets = [ApplicationLogFileWrapper].
2016-11-24T20:21:20.210Z : Custom rule filters can be applied to this target, Filter Count = [3].
2016-11-24T20:21:20.211Z : Read Custom Filter, Filter = [contains('${message}', 'GET: http://bot.whatismyipaddress.com')], Action = [Ignore], Type = [NLog.Filters.ConditionBasedFilter].
2016-11-24T20:21:20.211Z : Read Custom Filter, Filter = [contains('${message}', 'POST: https://connect.emby.media/service/Servers?')], Action = [Ignore], Type = [NLog.Filters.ConditionBasedFilter].
2016-11-24T20:21:20.211Z : Read Custom Filter, Filter = [contains('${message}', 'GET: https://connect.emby.media/service/ServerAuthorizations?')], Action = [Ignore], Type = [NLog.Filters.ConditionBasedFilter].
2016-11-24T20:21:20.246Z : SET LogSeverity, _severity = [Debug], value = [Debug]
2016-11-24T20:21:20.246Z : AddConsoleOutput called.
2016-11-24T20:21:20.246Z : RemoveTarget called, name = [ConsoleTargetWrapper].
2016-11-24T20:21:20.247Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:20.247Z : AddLogTarget called, target.Name = [ConsoleTargetWrapper], level = [Debug].
2016-11-24T20:21:20.247Z : GetLogLevel called, severity = [Debug].
2016-11-24T20:21:20.247Z : AddCustomFilters called, defaultLoggerNamePattern = [*], defaultRule.LoggerNamePattern = [*].
2016-11-24T20:21:20.253Z : Custom Configuration Loaded, Rule Count = [1].
2016-11-24T20:21:20.253Z : Read Custom Rule, LoggerNamePattern = [*], Targets = [ApplicationLogFileWrapper].
2016-11-24T20:21:20.253Z : Ignoring custom rule as [Target] does not match.
2016-11-24T20:21:20.307Z : GetLogger called, name = [Main].
2016-11-24T20:21:20.335Z : GetLogger called, name = [FileSystem].
2016-11-24T20:21:20.378Z : GetLogger called, name = [ImageMagick].
2016-11-24T20:21:20.419Z : GetLogger called, name = [SystemEvents].
2016-11-24T20:21:20.420Z : GetLogger called, name = [NetworkManager].
2016-11-24T20:21:20.441Z : GetLogger called, name = [XmlSerializer].
2016-11-24T20:21:20.443Z : GetLogger called, name = [ServerConfigurationManager].
2016-11-24T20:21:20.673Z : GetLogger called, name = [App].
2016-11-24T20:21:20.756Z : GetLogger called, name = [JsonSerializer].
2016-11-24T20:21:20.848Z : SET LogSeverity, _severity = [Debug], value = [Debug]
2016-11-24T20:21:20.907Z : GetLogger called, name = [TaskManager].
2016-11-24T20:21:20.908Z : GetLogger called, name = [HttpClient].
2016-11-24T20:21:20.910Z : GetLogger called, name = [SocketFactory].
2016-11-24T20:21:20.911Z : GetLogger called, name = [SecurityManager].
2016-11-24T20:21:20.911Z : GetLogger called, name = [InstallationManager].
2016-11-24T20:21:20.913Z : GetLogger called, name = [HttpResultFactory].
2016-11-24T20:21:20.913Z : GetLogger called, name = [LocalizationManager].
2016-11-24T20:21:20.935Z : GetLogger called, name = [UserDataManager].
2016-11-24T20:21:20.938Z : GetLogger called, name = [SqliteUserRepository].
2016-11-24T20:21:20.970Z : GetLogger called, name = [SqliteDisplayPreferencesRepository].
2016-11-24T20:21:20.970Z : GetLogger called, name = [SqliteItemRepository].
2016-11-24T20:21:20.975Z : GetLogger called, name = [SqliteFileOrganizationRepository].
2016-11-24T20:21:20.979Z : GetLogger called, name = [AuthenticationRepository].
2016-11-24T20:21:20.983Z : GetLogger called, name = [SyncRepository].
2016-11-24T20:21:20.986Z : GetLogger called, name = [UserManager].
2016-11-24T20:21:20.992Z : GetLogger called, name = [LibraryMonitor].
2016-11-24T20:21:20.993Z : GetLogger called, name = [ProviderManager].
2016-11-24T20:21:21.051Z : GetLogger called, name = [HttpServer].
2016-11-24T20:21:21.065Z : GetLogger called, name = [ServerManager].
2016-11-24T20:21:21.067Z : GetLogger called, name = [ImageProcessor].
2016-11-24T20:21:21.069Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:21.089Z : GetLogger called, name = [SyncManager].
2016-11-24T20:21:21.089Z : GetLogger called, name = [DtoService].
2016-11-24T20:21:21.090Z : GetLogger called, name = [ConnectManager].
2016-11-24T20:21:21.105Z : GetLogger called, name = [DeviceManager].
2016-11-24T20:21:21.105Z : GetLogger called, name = [DeviceManager].
2016-11-24T20:21:21.106Z : GetLogger called, name = [FileOrganizationService].
2016-11-24T20:21:21.106Z : GetLogger called, name = [ChannelManager].
2016-11-24T20:21:21.107Z : GetLogger called, name = [MediaSourceManager].
2016-11-24T20:21:21.108Z : GetLogger called, name = [SessionManager].
2016-11-24T20:21:21.109Z : GetLogger called, name = [Dlna].
2016-11-24T20:21:21.109Z : GetLogger called, name = [UpnpConnectionManager].
2016-11-24T20:21:21.110Z : GetLogger called, name = [CollectionManager].
2016-11-24T20:21:21.110Z : GetLogger called, name = [PlaylistManager].
2016-11-24T20:21:21.111Z : GetLogger called, name = [UpnpContentDirectory].
2016-11-24T20:21:21.112Z : GetLogger called, name = [MediaReceiverRegistrar].
2016-11-24T20:21:21.112Z : GetLogger called, name = [NotificationManager].
2016-11-24T20:21:21.112Z : GetLogger called, name = [SubtitleManager].
2016-11-24T20:21:21.112Z : GetLogger called, name = [IDeviceDiscovery].
2016-11-24T20:21:21.113Z : GetLogger called, name = [ChapterManager].
2016-11-24T20:21:21.116Z : GetLogger called, name = [MediaEncoder].
2016-11-24T20:21:21.118Z : GetLogger called, name = [SharingRepository].
2016-11-24T20:21:21.121Z : GetLogger called, name = [ActivityRepository].
2016-11-24T20:21:21.131Z : GetLogger called, name = [ActivityManager].
2016-11-24T20:21:21.131Z : GetLogger called, name = [SubtitleEncoder].
2016-11-24T20:21:21.136Z : GetLogger called, name = [SqliteUserDataRepository].
2016-11-24T20:21:21.170Z : GetLogger called, name = [SqliteNotificationsRepository].
2016-11-24T20:21:21.173Z : GetLogger called, name = [BaseItem].
2016-11-24T20:21:21.209Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:21.346Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:21.391Z : GetLogger called, name = [Lucene].
2016-11-24T20:21:22.406Z : GetLogger called, name = [SessionWebSocketListener].
2016-11-24T20:21:22.528Z : GetLogger called, name = [MovieDbEpisodeImageProvider].
2016-11-24T20:21:22.623Z : GetLogger called, name = [MovieDbSeasonProvider].
2016-11-24T20:21:22.627Z : GetLogger called, name = [MovieDbEpisodeProvider].
2016-11-24T20:21:22.770Z : GetLogger called, name = [OpenSubtitleDownloader].
2016-11-24T20:21:22.776Z : GetLogger called, name = [LiveTvMediaSourceProvider].
2016-11-24T20:21:22.792Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:22.792Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:22.792Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:24.511Z : GetLogger called, name = [ChapterImagesTask].
2016-11-24T20:21:24.526Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:24.530Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:24.540Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:24.541Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:24.542Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:24.542Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:24.544Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:24.545Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:24.547Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:24.548Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:24.548Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:24.548Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:24.550Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:24.550Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:24.551Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:24.552Z : GetLogger called, name = [SystemId].
2016-11-24T20:21:24.553Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:24.554Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:24.555Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:24.557Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:24.558Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:24.559Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:24.559Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:24.561Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:24.561Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:24.562Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:24.562Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:24.562Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:24.563Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:24.564Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:24.564Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:24.792Z : GetLogger called, name = [Registration Loader].
2016-11-24T20:21:24.814Z : GetLogger called, name = [PortMapper].
2016-11-24T20:21:24.819Z : GetLogger called, name = [Dlna].
2016-11-24T20:21:24.821Z : GetLogger called, name = [PortMapper].
2016-11-24T20:21:24.836Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:24.839Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:24.935Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:24.963Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.090Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.093Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.168Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.189Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.190Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.247Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.248Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.251Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.277Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.279Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.280Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.283Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.285Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.286Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.288Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.290Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.291Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.294Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.295Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.297Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.299Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.300Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.302Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.305Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.307Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.309Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.309Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.310Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.311Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.312Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.314Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.316Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.318Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.320Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.322Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.323Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.327Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.363Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.373Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.373Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.375Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.377Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.377Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.380Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.382Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.386Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.386Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.387Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.388Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.388Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.389Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.389Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.389Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.389Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.389Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.390Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.392Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.393Z : RemoveConsoleOutput called.
2016-11-24T20:21:25.393Z : RemoveTarget called, name = [ConsoleTargetWrapper].
2016-11-24T20:21:25.459Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.459Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.559Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:25.559Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:27.673Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:27.769Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:28.076Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:28.076Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:28.076Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:28.077Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:28.077Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:28.077Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:28.077Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:28.078Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:28.078Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:28.078Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:28.078Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:28.078Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:28.078Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:28.079Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:42.439Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:42.849Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:42.860Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:42.862Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:42.864Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:42.866Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:42.868Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:42.870Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:43.017Z : GET LogSeverity, _severity = [Debug].
2016-11-24T20:21:43.124Z : GET LogSeverity, _severity = [Debug].
```

James

**Comment by SvenVandenbrande** [comment]
Also VS2017? :) @LukePulverenti

**Comment by solabc16** [comment]
Hello @SvenVandenbrande - today's commits were to get the latest beta built on VS2017 using the MediaBrowser solution instead of the MediaBrowser.Mono solution. This was for Synology/XPEnology - i.e. a Mono target.

**Comment by LukePulverenti** [comment]
Closing. No longer using nlog.

**Pull request closed without merging**
