### PR TITLE
Allow build in Visual 2015 Update Fody

### PR DESCRIPTION
**Pull request by jose-pr**

### CODE REVIEW

**Comment by LukePulverenti** [comment]
Awesome, thanks. Does it still build in 2013?

**Comment by jose-pr** [comment]
I dont know as i dont have it. but i think it should, someone with 2013 should download/fork/clone the branch it and try to compile it.

**Comment by jose-pr** [comment]
Test on 2013 and 2015 compiled succesfully

**Comment by LukePulverenti** [comment]
I've had to revert this. It did not build for me out of the box on 2013 and I do not have time to debug it right now. Also, it caused the solution to prompt to run nuget restore but we need that disabled, which means any changes to package files have to be checked into source.

**Pull request merged**
