### PR TITLE
Hide unused DLNA option

### PR DESCRIPTION
**Pull request by softworkz**
This option does not seem to be used anywhere

### CODE REVIEW

**Comment by LukePulverenti** [comment]
Technically it is actually used everywhere since byte range requests for transcoding are always ignored. It's just the opposite scenario that is not supported. Since the toggle doesn't work we can hide it.

**Comment by softworkz** [comment]
Sure, but when we start experimenting with range requests, this could raise wrong expectations, so I thought: better not show that.  (but we don't delete it - maybe some day things change...)

**Comment by LukePulverenti** [comment]
It has to remain. There is one device that needs it, and others that won't be able to function with it. So it has to be controllable either way.

**Comment by softworkz** [comment]
>  (but we don't delete it - maybe some day things change...)

Sorry, I meant to say the same: we should _not_ delete it!

**Pull request merged**
