### PR TITLE
Organize-Dialog: Migrate to emby-inputs and include movie organization

### PR DESCRIPTION
**Pull request by softworkz**

### CODE REVIEW

**Comment by softworkz** [comment]
Rebased...

**Comment by softworkz** [comment]
Rebased and changed tab-selection to html SELECT element.

**Comment by softworkz** [comment]
Rebased.

**Comment by LukePulverenti** [comment]
I took care of the input changes because I became a little anxious to drop polymer, so that part is done.

**Comment by softworkz** [comment]
Rebased - everything fixed and working again!

**Comment by softworkz** [comment]
Rebased and removed duplicate definition

**Comment by softworkz** [comment]
Rebased.

**Comment by LukePulverenti** [comment]
Are there any straight up bug fixes from here that should be integrated separately from movie support? If so then please let me know. Thanks.

**Comment by LukePulverenti** [comment]
I'm in process of publishing auto-organize as a plugin. See: https://github.com/MediaBrowser/emby-auto-organize

You are welcome to take some ownership and add whatever features you like. Thanks.

**Pull request closed without merging**
