### PR TITLE
Daily Episode Support for Auto-Organize - Closes #1145

### LINKED ISSUE #1145: Improve support for daily episodes
Currently, we are able to parse the date out of the filename but we don't support internet metatdata.

The following areas will need adjustment:

- Tvdb episode provider
- MissingEpisodeProvider
- AutoOrganize
- Season/Series methods to get lists of episodes

### PR DESCRIPTION
**Pull request by softworkz**

### CODE REVIEW

**Comment by softworkz** [comment]
This also includes changes from PR #1202 since it was built on top of it

**Comment by softworkz** [comment]
I reverted my changes and adjusted autoorganize to use the latest provider change

**Comment by LukePulverenti** [comment]
What's left with this one? There are 41 files changed, and lots of things that aren't directly related to daily episodes. Thanks.

**Comment by softworkz** [comment]
Hold on, I will clear this up..

**Comment by softworkz** [comment]
I'm closing this. The only functional difference I had in my code  was better propagation of errors to the user and in the log.

**Pull request closed without merging**
