### PR TITLE
OmdbProvider: Fix for data fields containing "N/A"

### PR DESCRIPTION
**Pull request by softworkz**
omdbapi.com likes to return "N/A" for fields whithout content.

This can cause problems when metadata results are merged: During merge, the "N/A" value is used, even if other providers (of lower priority) had better data.

The previous implementation had handled this problem for certain fields only.

This commit solves the problem for all fields in a generic way..

### CODE REVIEW

**Comment by LukePulverenti** [comment]
Which fields is this currently not working for?

**Comment by softworkz** [comment]
For **Rated** and **Plot** I had actual cases where i got "N/A" values.
The result was that the Overview was "N/A" and the Rating was "N/A", while another provider would have had real information.

**Comment by softworkz** [comment]
For other fields we use .TryParse(), which of course fails for "N/A" entries, but I think a generic replacement of these values is a cleaner solution.

**Comment by softworkz** [comment]
Rebased and reworked without using TypeDescriptor

**Pull request merged**
