### PR TITLE
Auto-Organize: PathTooLongException on source file should not break auto-organize task

### PR DESCRIPTION
**Pull request by softworkz**
PathTooLongException can not only occur with long destination paths but
also with too long file names of files contained in a watch folder.
Previously this condition caused the auto-organize task to break.

With this change, we still log the exception, but auto-organize
processing will continue to handle all other files.

### CODE REVIEW

**Comment by softworkz** [comment]
Please see also: http://emby.media/community/index.php?/topic/25946-auto-organize-has-stopped-working/

**Comment by LukePulverenti** [comment]
How about instead give the function a name to indicate it's a filter to determine what files to organize. then move the length check in there as well. the purpose of the try/catch will then be to handle any possible error when querying the file info and returning false if something is encountered.

**Comment by softworkz** [comment]
Oh well, the length check is already performed in the function *IsValidVideoFile*:
In case of a too long path, the FileInfo.FullName property will cause the exception.

If you are referring to the minimum file length check - these two are actually very different issues:

* Path too long: Throw and log error but continue processing all other watched files
* File too small: Silently ignore since it may be just a trailer or sample file

**Comment by softworkz** [comment]
But of course I could rename it to *FilterValidVideoFile*...

**Comment by softworkz** [comment]
I renamed the function to FilterValidVideoFile as requested.

**Comment by softworkz** [comment]
Thank you! :-)

**Pull request merged**
