### PR TITLE
Fody Update

### PR DESCRIPTION
**Pull request by jose-pr**
Update to fody so that it compiles on 2015. Made sure to check that not other settings such as Nuget timestamp where set in https://github.com/MediaBrowser/Emby/pull/1488

### CODE REVIEW

**Comment by LukePulverenti** [comment]
The windows build script under tools -> windows_build_script fails. Try cloning the repo and running the script directly without first running nuget restore.

Build FAILED.

"C:\Dev\Emby.fody\MediaBrowser.sln" (Clean;Build target) (1) ->
"C:\Dev\Emby.fody\MediaBrowser.Model.net35\MediaBrowser.Model.net35.csproj" (default target) (20:2) ->
(CoreCompile target) -> 
  c:\Dev\Emby.fody\MediaBrowser.Model\Querying\ItemQuery.cs(309,13): warning CS0612: 'MediaBrowser.Model.Querying.ItemQuery.Artists' is obsolete [C:\Dev\Emby.fody\MediaBrowser.Model.net35\MediaBrowser.Model.net35.csproj]
  c:\Dev\Emby.fody\MediaBrowser.Model\Querying\ItemQuery.cs(310,13): warning CS0612: 'MediaBrowser.Model.Querying.ItemQuery.Studios' is obsolete [C:\Dev\Emby.fody\MediaBrowser.Model.net35\MediaBrowser.Model.net35.csproj]
  c:\Dev\Emby.fody\MediaBrowser.Model\Dto\BaseItemDto.cs(1091,50): warning CS0067: The event 'MediaBrowser.Model.Dto.BaseItemDto.PropertyChanged' is never used [C:\Dev\Emby.fody\MediaBrowser.Model.net35\MediaBrowser.Model.net35.csproj]
  c:\Dev\Emby.fody\MediaBrowser.Model\Dto\BaseItemPerson.cs(60,50): warning CS0067: The event 'MediaBrowser.Model.Dto.BaseItemPerson.PropertyChanged' is never used [C:\Dev\Emby.fody\MediaBrowser.Model.net35\MediaBrowser.Model.net35.csproj]
  c:\Dev\Emby.fody\MediaBrowser.Model\Dto\ChapterInfoDto.cs(42,50): warning CS0067: The event 'MediaBrowser.Model.Dto.ChapterInfoDto.PropertyChanged' is never used [C:\Dev\Emby.fody\MediaBrowser.Model.net35\MediaBrowser.Model.net35.csproj]
  c:\Dev\Emby.fody\MediaBrowser.Model\Dto\StudioDto.cs(47,50): warning CS0067: The event 'MediaBrowser.Model.Dto.StudioDto.PropertyChanged' is never used [C:\Dev\Emby.fody\MediaBrowser.Model.net35\MediaBrowser.Model.net35.csproj]
  c:\Dev\Emby.fody\MediaBrowser.Model\Dto\UserDto.cs(147,50): warning CS0067: The event 'MediaBrowser.Model.Dto.UserDto.PropertyChanged' is never used [C:\Dev\Emby.fody\MediaBrowser.Model.net35\MediaBrowser.Model.net35.csproj]
  c:\Dev\Emby.fody\MediaBrowser.Model\Dto\UserItemDataDto.cs(78,50): warning CS0067: The event 'MediaBrowser.Model.Dto.UserItemDataDto.PropertyChanged' is never used [C:\Dev\Emby.fody\MediaBrowser.Model.net35\MediaBrowser.Model.net35.csproj]
  c:\Dev\Emby.fody\MediaBrowser.Model\Entities\DisplayPreferences.cs(17,50): warning CS0067: The event 'MediaBrowser.Model.Entities.DisplayPreferences.PropertyChanged' is never used [C:\Dev\Emby.fody\MediaBrowser.Model.net35\MediaBrowser.Model.net35.csproj]
  c:\Dev\Emby.fody\MediaBrowser.Model\LiveTv\BaseTimerInfoDto.cs(13,50): warning CS0067: The event 'MediaBrowser.Model.LiveTv.BaseTimerInfoDto.PropertyChanged' is never used [C:\Dev\Emby.fody\MediaBrowser.Model.net35\MediaBrowser.Model.net35.csproj]
  c:\Dev\Emby.fody\MediaBrowser.Model\LiveTv\ChannelInfoDto.cs(124,50): warning CS0067: The event 'MediaBrowser.Model.LiveTv.ChannelInfoDto.PropertyChanged' is never used [C:\Dev\Emby.fody\MediaBrowser.Model.net35\MediaBrowser.Model.net35.csproj]
  c:\Dev\Emby.fody\MediaBrowser.Model\Session\SessionInfoDto.cs(119,50): warning CS0067: The event 'MediaBrowser.Model.Session.SessionInfoDto.PropertyChanged' is never used [C:\Dev\Emby.fody\MediaBrowser.Model.net35\MediaBrowser.Model.net35.csproj]


"C:\Dev\Emby.fody\MediaBrowser.sln" (Clean;Build target) (1) ->
"C:\Dev\Emby.fody\MediaBrowser.Controller\MediaBrowser.Controller.csproj" (default target) (5:14) ->
"C:\Dev\Emby.fody\MediaBrowser.Common\MediaBrowser.Common.csproj" (default target) (3:16) ->
"C:\Dev\Emby.fody\MediaBrowser.Model\MediaBrowser.Model.csproj" (default target) (4:18) ->
(EnsureNuGetPackageBuildImports target) -> 
  C:\Dev\Emby.fody\MediaBrowser.Model\MediaBrowser.Model.csproj(466,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Fody.1.29.2\build\dotnet\Fody.targets.


"C:\Dev\Emby.fody\MediaBrowser.sln" (Clean;Build target) (1) ->
"C:\Dev\Emby.fody\MediaBrowser.Model.Portable\MediaBrowser.Model.Portable.csproj" (default target) (18:2) ->
  C:\Dev\Emby.fody\MediaBrowser.Model.Portable\MediaBrowser.Model.Portable.csproj(1253,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Fody.1.29.2\build\portable-net+sl+win+wpa+wp\Fody.targets.

    12 Warning(s)
    2 Error(s)

Time Elapsed 00:00:01.57

**Comment by LukePulverenti** [comment]
Similarly, once that is solved, we're going to need to check the linux build scripts as well.

**Comment by jose-pr** [comment]
Problem came from gitignore file ignoring files under /bin in fody and .pdb files

**Comment by LukePulverenti** [comment]
Ah ok. You can use the tortoise git shell extension to add them on a one-time basis. if you right click inside the folder -> add, then there's a checkbox to include ignored files

**Comment by jose-pr** [comment]
Added on git shell with git add -f 
should be good now

**Pull request merged**
