### PR TITLE
Updates To EmbyTV with emphasis on merging multiple sources

### PR DESCRIPTION
**Pull request by jose-pr**
[WIP] Based on  #1479 taking my time to clean it up as much as possible and make smaller commits.

### CODE REVIEW

**Comment by jose-pr** [comment]
@LukePulverenti  I think it looks good only thing left is to put it on dev to find any bugs that i may have missed.

**Comment by LukePulverenti** [comment]
I haven't had a chance to look into it yet, but I will soon. I actually just took a quick glance and I do really like the javascript refactorings, but try to avoid changes that aren't directly related to multiple tuner sources, as it's just going to keep increasing the time & complexity factor.

**Comment by LukePulverenti** [comment]
But, just to add - I don't want to discourage you from making those other improvements, it would just be ideal to slice them into separate pull requests.

**Comment by jose-pr** [comment]
@LukePulverenti  Did you have a chance to look over it?

**Comment by LukePulverenti** [comment]
merged manually.

**Pull request closed without merging**
