### PR TITLE
Authentication Provider 

### PR DESCRIPTION
**Pull request by jose-pr**
Adds the possibility of having plugins that provide authentication providers

### CODE REVIEW

**Comment by jose-pr** [comment]
Remake of #1885 @LukePulverenti  , this would be the base for additional authentication providers needs to have a way to add distinguishednames from the web to a user

**Comment by jose-pr** [comment]
Should allow for plugins that could provide for #1981 and #1146 
Should be easy to add a salt now for password #1074

**Comment by untotren** [comment]
@jose-pr what is the progress of this?

**Comment by untotren** [comment]
@jose-pr @LukePulverenti Are these conflicts able to be resolved?  It seems it is ready to go but being ignored for unknown reasons.

**Comment by SvenVandenbrande** [comment]
@untotren I think you first need to fix the conflicts before @LukePulverenti  can merge it.. :)

**Comment by jose-pr** [comment]
@untotren  I had to stop working on this as I have been busy (still am), also i think Emby was going to move to ASP Core and i was waiting for that until i made any other changes. I encourage anyone to continue working on this maybe even implement something like LetsEncrypt for secure ssl

**Comment by jose-pr** [comment]
@LukePulverenti Has the move to Net Core been done? Are there any major chances coming soon to the code/ especially in the authentication side? I was planning on putting some work into this maybe after the holidays.

**Comment by untotren** [comment]
@jose-pr you are a godsend.

**Comment by LukePulverenti** [comment]
@jose-pr yea if you want to start having discussions about work that needs to be done, I'm ready to start doing that. Thanks.

**Comment by untotren** [comment]
@jose-pr Did you get a chance to get back to Luke?^^^

**Comment by jose-pr** [comment]
I am waiting when i can just hit build in .net core. so i can test build easily and don't have to worry about using functions not available for net core/std. For now it still builds by default in mono / net 4.x

**Comment by LukePulverenti** [comment]
I ended up implementing a much smaller version of this, but conceptually similar with the modular authentication provider.

**Pull request closed without merging**
