### PR TITLE
Add Flac to Samsung direct play profile

### PR DESCRIPTION
**Pull request by ginjaninja1**
Add Flac to Samsung direct play profile.
Samsungs from 2012 support this..so if Flac support isnt universal for all Samsungs, it is most common...

### CODE REVIEW

**Comment by ginjaninja1** [comment]
My first pull request, needs to be checked

**Comment by ginjaninja1** [comment]
its apparent im confused by github, i thought i had replicated the structure before...i edited it again to include your suggestion..but i cant see my correction :-(

**Comment by tadams88** [comment]
It's there now, your second commit showed up in this pull request. Click commits up top to see the second commit showed up, and then click files changed to see the final outcome of the 2 commits.

**Comment by ginjaninja1** [comment]
thanks, its making a bit more sense...do i just wait now for an owner to accept or reject? is it submitted for review? do i need to close it to submit it?

**Comment by tadams88** [comment]
You are done. The Pull Request is submitted. One of the owners will review when they have time, and then they will either accept, reject, or ask for some changes. Might take a while, those guys have a lot on their plates.

**Comment by LukePulverenti** [comment]
Does this work for all samsungs? what year did they start supporting flac?

**Comment by ginjaninja1** [comment]
my 2012 model supports flac..i assume all later do as well ..but have not done any investigation..maybe a second samsung profile is a safer way to go..that said the number of unsupported tvs must be diminishing towards zero over time

**Comment by LukePulverenti** [comment]
merged manually

**Pull request closed without merging**
