### PR TITLE
User Authentication: Enable multiple domain providers for authentication.

### PR DESCRIPTION
**Pull request by jose-pr**
Allow the creation of domain providers plugins which the server can use to get users and groups from and the changes to enable this such as encryption/decryption of passwords, creation of local domain, move the configuration and policy settings from xml to the sql database. My goal after this is the creation of  LDAP authentication and the later on to expand on groups to be able to apply default policy by group to easily manage multiple individuals with similar settings.

Relates to  #1146 
I did the work in a local repo and will be updating this pull request with commits while i clean up my code.

### CODE REVIEW

**Comment by jose-pr** [comment]
CRUD operations are working in the users(policy, configuration and server user data) and the local_domain (local directory for user auth) database. Left is how to present the users from different domains in the login screen , which i cant think of how to do at the moment.

**Comment by jose-pr** [comment]
Domain now appears on the Login screen, username doesn't need to be the same as the presented name with the picture.

image

**Comment by jose-pr** [comment]
Little change in the way thing works, before external user where they own account now they are part of a local account that is created the first time a external user logs in.

**Comment by jose-pr** [comment]
Pretty much the base work is done the rest is to create a ldap plugin to test it with ldap and to create an interface in users to be able to set external auth in the server. Perhaps convert convert the connect connection to one provided by the new interface.

**Comment by LukePulverenti** [comment]
Jose - thanks! Just want you to know you're not being left hanging. I will start looking at this soon.

**Comment by jose-pr** [comment]
Will do multiple small pull requests to add features needed and may then reopen this pull based on the other ones.

**Comment by untotren** [comment]
@jose-pr is this still up to date? I want to use this so bad.

**Pull request closed without merging**
