### PR TITLE
Support QSV decoder for LiveTV

### PR DESCRIPTION
**Pull request by babgvant**
ProbeSizeOverride was added because the LiveTV probe doesn't need to be that big to figure out codec.

### CODE REVIEW

**Comment by LukePulverenti** [comment]
Andy I can't merge this in. We already have the code to probe live tv but i had to comment it out right now because it causes multiple streams to be opened and closed with the tuners which can create tuner conflicts. It will have to wait until i have a chance to buffer the stream in Emby server.

**Comment by babgvant** [comment]
Where is the existing probe code?

**Comment by LukePulverenti** [comment]
In BaseTunerHost - AddMediaInfo

**Comment by babgvant** [comment]
The reason why it's causing trouble is probably the same problem fixed by using a small probe size (the override I added).

**Comment by LukePulverenti** [comment]
No I mean the trouble is a different kind of trouble, as in other open streams get terminated, recordings fail, etc. We need to make sure the entire playback session only opens one single stream.

**Comment by babgvant** [comment]
How does probing cause that problem? As long as the original stream isn't terminated HDHR tuner locking shouldn't allow that to happen.

**Comment by LukePulverenti** [comment]
Because ffprobe opens one stream, closes it, then the video player or ffmpeg opens a second one.

**Comment by babgvant** [comment]
That's not how HDHR tuner locking is supposed to work. HTTP streams only hold a lock as long as they are open, when it closes it frees the tuner. The second request would either take the previous (now free) tuner, or another one if it's free. If probing breaks an existing stream, then the tuner isn't locked. Which means the DVR implementation is flawed (cough MythTV), or there's a bug in SD's code.

If the server is overlapping the probe and request, that might cause failures, but it doesn't sound like that's what's happening.

**Comment by LukePulverenti** [comment]
You're right, but their problem becomes our problem so for now I had to disable it.

**Comment by babgvant** [comment]
Have you escalated it to them?

**Pull request closed without merging**
