### PR TITLE
OmdbItemProvider: Use search instead of title API

### PR DESCRIPTION
**Pull request by softworkz**
In my configuration, the Omdb provider is the first in the list for
movie metadata. This was the default at the time I installed MB and I
never changed that (don't know what the current defaults are for a new
installation).
When I use the identify command for movies in the metadata editor, I
always get a single result only. This is due to the fact that the Omdb
provider used the title API with "t=moviename", while there is also a
search api with "s=moviename" which will return multiple results.

This commit modifies the OmdbItemProvider to use the search API variant
and enable returning multiple results

### CODE REVIEW

**Comment by softworkz** [comment]
I should note that there is a slight drawback: The search API does not return images. But when trying to identify a movie, a single result is not helpful, even if it comes with an image...

**Comment by LukePulverenti** [comment]
can you submit a request to the developer to add it? thanks.

**Comment by softworkz** [comment]
OK, I will try! If he'll do, we are still set - no additional change would be required..

**Comment by softworkz** [comment]
OK, I sent a message to the owner of omdbapi. I sent you a copy as PM on http://emby.media/community (had no other idea how to send you something)

Let's hope he will agree - at least I had a good argument...

**Pull request merged**
